/**
 * Industry definitions for the Manya Pulse tool.
 * Each industry has compliance frameworks, data classifications,
 * redaction rules, access policies, and message types.
 */

export const INDUSTRIES = {
  healthcare: {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'HIPAA-compliant data handling, PHI protection, medical audit trails, and HL7/FHIR-aware processing.',
    frameworks: ['HIPAA', 'HITECH', 'GDPR-Health', 'POPIA-Health'],
    dataClassifications: ['phi', 'pii', 'medical-record', 'prescription', 'diagnosis', 'insurance'],
    redactionPreset: 'phi',
    accessTemplate: 'healthcare-rbac',
    stampTemplate: 'medical-audit',
    signalTypes: ['hl7-message', 'fhir-resource', 'lab-result', 'prescription-order'],
    vaultNamespace: 'healthcare',
    complianceNotes: [
      'All PHI must be encrypted at rest and in transit (AES-256 or equivalent)',
      'Access to patient records requires role-based authorization with audit logging',
      'Data retention policies must comply with HIPAA minimum 6-year requirement',
      'Breach notification required within 60 days of discovery',
    ],
  },
  finance: {
    id: 'finance',
    name: 'Finance',
    description: 'PCI-DSS compliant payment processing, SWIFT messaging, transaction signing, and financial audit trails.',
    frameworks: ['PCI-DSS', 'SOX', 'Basel-III', 'GDPR-Finance', 'POPIA-Finance'],
    dataClassifications: ['pci', 'pii', 'pan', 'transaction', 'account', 'swift'],
    redactionPreset: 'financial',
    accessTemplate: 'finance-rbac',
    stampTemplate: 'financial-audit',
    signalTypes: ['swift-message', 'payment-instruction', 'trade-confirmation', 'settlement-notice'],
    vaultNamespace: 'finance',
    complianceNotes: [
      'Cardholder data (PAN, CVV) must never be stored in cleartext',
      'All financial transactions require cryptographic timestamp proof',
      'Access to payment systems requires multi-factor authentication',
      'Audit logs must be immutable and retained for 7 years minimum',
    ],
  },
  legal: {
    id: 'legal',
    name: 'Legal',
    description: 'Document timestamping, chain of custody, attorney-client privilege classification, and eDiscovery support.',
    frameworks: ['GDPR-Legal', 'POPIA-Legal', 'Attorney-Client Privilege', 'eDiscovery-ESI'],
    dataClassifications: ['privileged', 'confidential', 'work-product', 'client-data', 'court-filing'],
    redactionPreset: 'pii',
    accessTemplate: 'legal-rbac',
    stampTemplate: 'chain-of-custody',
    signalTypes: ['legal-notice', 'court-filing', 'privilege-log', 'discovery-request'],
    vaultNamespace: 'legal',
    complianceNotes: [
      'Attorney-client privilege must be preserved with strict access controls',
      'Chain of custody must be tamper-proof with cryptographic proof at each step',
      'Document retention must comply with jurisdiction-specific requirements',
      'Privilege logs must track all access to protected communications',
    ],
  },
  iot: {
    id: 'iot',
    name: 'IoT & Manufacturing',
    description: 'Lightweight compression for constrained devices, firmware integrity, sensor data provenance, and command signing.',
    frameworks: ['IEC-62443', 'NIST-IoT', 'ISO-27001-IoT'],
    dataClassifications: ['telemetry', 'firmware', 'command', 'sensor-data', 'config', 'ota-update'],
    redactionPreset: 'pii',
    accessTemplate: 'device-rbac',
    stampTemplate: 'device-provenance',
    signalTypes: ['device-command', 'sensor-reading', 'firmware-update', 'device-heartbeat'],
    vaultNamespace: 'iot',
    complianceNotes: [
      'Firmware updates must be signed and verified before installation',
      'Device identity must be authenticated before command acceptance',
      'Sensor data must include integrity proof for tamper detection',
      'OTA updates require rollback capability and audit trail',
    ],
  },
  government: {
    id: 'government',
    name: 'Government & Defense',
    description: 'Security clearance levels, classified data handling, sovereign data compliance, and intelligence audit trails.',
    frameworks: ['NIST-800-53', 'ITAR', 'CUI', 'FIPS-140-2', 'POPIA-Government'],
    dataClassifications: ['classified', 'secret', 'top-secret', 'cui', 'fouo', 'sci'],
    redactionPreset: 'all',
    accessTemplate: 'clearance-rbac',
    stampTemplate: 'intelligence-audit',
    signalTypes: ['classified-message', 'intelligence-report', 'clearance-update', 'ops-order'],
    vaultNamespace: 'government',
    complianceNotes: [
      'Classified data requires encryption meeting FIPS-140-2 standards',
      'Access based on security clearance level and need-to-know',
      'All access attempts must be logged even if denied',
      'Data sovereignty must be maintained — no cross-border storage without approval',
    ],
  },
  education: {
    id: 'education',
    name: 'Education',
    description: 'Student data privacy (FERPA), grading integrity, research provenance, and academic audit trails.',
    frameworks: ['FERPA', 'GDPR-Education', 'COPPA', 'POPIA-Education'],
    dataClassifications: ['ferpa-protected', 'student-record', 'grade', 'research-data', 'directory-info'],
    redactionPreset: 'pii',
    accessTemplate: 'education-rbac',
    stampTemplate: 'academic-audit',
    signalTypes: ['grade-notification', 'enrollment-event', 'transcript-request', 'research-submission'],
    vaultNamespace: 'education',
    complianceNotes: [
      'Student records are protected under FERPA — consent required for disclosure',
      'Grading changes must be timestamped with immutable audit trail',
      'Research data must preserve provenance chain for reproducibility',
      'Directory information may be public unless student opts out',
    ],
  },
  retail: {
    id: 'retail',
    name: 'Retail & E-Commerce',
    description: 'Payment data protection, inventory chain tracking, customer PII handling, and promotional compliance.',
    frameworks: ['PCI-DSS-Retail', 'GDPR-Retail', 'CAN-SPAM', 'POPIA-Retail'],
    dataClassifications: ['payment', 'customer-pii', 'inventory', 'pricing', 'loyalty-data'],
    redactionPreset: 'financial',
    accessTemplate: 'retail-rbac',
    stampTemplate: 'supply-chain-audit',
    signalTypes: ['order-confirmation', 'payment-receipt', 'inventory-update', 'loyalty-event'],
    vaultNamespace: 'retail',
    complianceNotes: [
      'Customer payment data must comply with PCI-DSS tokenization requirements',
      'Inventory chain requires provenance tracking from source to sale',
      'Customer consent required for marketing communications (CAN-SPAM/GDPR)',
      'Price changes must be timestamped for audit and compliance',
    ],
  },
  energy: {
    id: 'energy',
    name: 'Energy & Utilities',
    description: 'SCADA data integrity, regulatory compliance, sensor data provenance, and critical infrastructure protection.',
    frameworks: ['NERC-CIP', 'IEC-62351', 'NIST-Energy', 'POPIA-Energy'],
    dataClassifications: ['scada', 'meter-data', 'grid-telemetry', 'outage-report', 'safety-record'],
    redactionPreset: 'pii',
    accessTemplate: 'energy-rbac',
    stampTemplate: 'scada-audit',
    signalTypes: ['meter-reading', 'grid-command', 'outage-alert', 'safety-notification'],
    vaultNamespace: 'energy',
    complianceNotes: [
      'SCADA commands must be cryptographically signed and verified',
      'Critical infrastructure access requires multi-factor authentication',
      'Meter data must be tamper-evident with integrity proof',
      'Regulatory reports must use immutable audit trails',
    ],
  },
  telecom: {
    id: 'telecom',
    name: 'Telecommunications',
    description: 'Call data record integrity, network telemetry protection, subscriber PII handling, and lawful intercept compliance.',
    frameworks: ['GDPR-Telecom', 'CALEA', '3GPP-Security', 'POPIA-Telecom'],
    dataClassifications: ['cdr', 'subscriber-pii', 'network-telemetry', 'lawful-intercept', 'location-data'],
    redactionPreset: 'pii',
    accessTemplate: 'telecom-rbac',
    stampTemplate: 'telecom-audit',
    signalTypes: ['cdr-record', 'network-event', 'provisioning-command', 'intercept-warrant'],
    vaultNamespace: 'telecom',
    complianceNotes: [
      'Call detail records must be integrity-protected and tamper-evident',
      'Subscriber PII requires encryption and access controls',
      'Lawful intercept must be auditable with strict access controls',
      'Location data is classified as sensitive and requires explicit consent',
    ],
  },
  gaming: {
    id: 'gaming',
    name: 'Gaming & Entertainment',
    description: 'Asset packaging and compression, anti-cheat integrity verification, digital rights management, and player data protection.',
    frameworks: ['GDPR-Gaming', 'COPPA-Gaming', 'DMCA', 'POPIA-Gaming'],
    dataClassifications: ['player-data', 'game-state', 'asset', 'anti-cheat', 'transaction', 'chat-log'],
    redactionPreset: 'pii',
    accessTemplate: 'gaming-rbac',
    stampTemplate: 'game-audit',
    signalTypes: ['game-event', 'match-result', 'asset-delivery', 'anti-cheat-report'],
    vaultNamespace: 'gaming',
    complianceNotes: [
      'Player data must be protected under GDPR with right to deletion',
      'Game assets must be integrity-verified to prevent tampering',
      'Anti-cheat reports must be tamper-proof for fair play enforcement',
      'In-game transactions require cryptographic proof for dispute resolution',
    ],
  },
};

export const INDUSTRY_IDS = Object.keys(INDUSTRIES);
