/**
 * Transport mode definitions for the Manya Transport & Logistics tool.
 * Covers Aviation (air cargo), Maritime (sea freight), Road (trucking),
 * Rail (rail freight), and Multimodal (combined transport).
 *
 * Each mode declares its regulatory frameworks, identifier formats,
 * dangerous-goods rules, customs regimes, and signal types.
 */

export const MODES = {
  aviation: {
    id: 'aviation',
    name: 'Aviation & Air Cargo',
    description: 'Air freight and cargo aviation with IATA standards, AWB tracking, flight number validation, dangerous goods (IATA-DGR), and high-value shipment compliance.',
    frameworks: ['ICAO-Annex-18', 'IATA-DGR', 'IATA-Cargo-XML', 'Warsaw-Convention', 'Montreal-Convention-1999', 'ACI-Cargo'],
    dataClassifications: ['awb-number', 'flight-number', 'aircraft-registration', 'cargo-manifest', 'dangerous-goods', 'airway-bill-pii'],
    redactionPreset: 'transport-aviation',
    accessTemplate: 'aviation-rbac',
    stampTemplate: 'aviation-audit',
    signalTypes: ['flight-departure', 'flight-arrival', 'awb-issued', 'cargo-loaded', 'cargo-unloaded', 'flight-delay'],
    vaultNamespace: 'transport-aviation',
    identifierFormats: ['awb-11-digit', 'awb-8-digit-prefix', 'flight-iata', 'icao-aircraft'],
    containerTypes: ['ULD-AKE', 'ULD-PAG', 'ULD-PMC', 'ULD-RKN', 'ULD-LD3'],
    complianceNotes: [
      'Air Waybill numbers must pass IATA modulo-11 check-digit validation',
      'Dangerous goods shipments require IATA-DGR shipper declaration with cryptographic sign-off',
      'Aircraft registration numbers must follow ICAO Annex 7 format (e.g. ZS-ABC for South Africa)',
      'High-value cargo (>$1M) requires dual-control chain of custody with timestamp proof at each handover',
      'Flight number changes must be logged with original and new flight identifiers for audit trail',
    ],
  },
  maritime: {
    id: 'maritime',
    name: 'Maritime & Sea Freight',
    description: 'Container shipping, port operations, vessel tracking (AIS), IMO number verification, Bill of Lading integrity, and SOLAS/MARPOL compliance.',
    frameworks: ['SOLAS', 'MARPOL', 'IMO-IMDG-Code', 'IMO-FAL-Convention', 'UNCLOS', 'ISPS-Code'],
    dataClassifications: ['imo-number', 'container-number', 'bill-of-lading', 'vessel-track', 'port-call', 'manifest-pii'],
    redactionPreset: 'transport-maritime',
    accessTemplate: 'maritime-rbac',
    stampTemplate: 'maritime-audit',
    signalTypes: ['vessel-arrival', 'vessel-departure', 'container-loaded', 'container-discharged', 'port-call', 'ais-position'],
    vaultNamespace: 'transport-maritime',
    identifierFormats: ['imo-7-digit', 'container-iso-6346', 'bl-number', 'unlocode', 'mmsi-9-digit'],
    containerTypes: ['20GP', '40GP', '40HC', '45HC', '20RF', '40RF', '20OT', '40OT', '20FR', '40FR'],
    complianceNotes: [
      'IMO numbers must pass the IMO 7-digit check-digit algorithm (sum of first 6 digits × positional weights, modulo 10)',
      'Container numbers must follow ISO 6346 format: 4 letters (owner + category) + 7 digits with check digit',
      'Bill of Lading numbers must be unique per carrier and timestamped at issuance',
      'AIS position data must be integrity-protected to prevent voyage tampering',
      'Dangerous goods stowage plans must comply with IMDG Code segregation requirements',
      'Port state control inspections require immutable audit trail of findings and remediation',
    ],
  },
  road: {
    id: 'road',
    name: 'Road & Trucking',
    description: 'Trucking operations, CMR consignment notes, vehicle tracking, tachograph compliance, ADR dangerous goods, and cross-border road transport.',
    frameworks: ['CMR-Convention', 'ADR-2023', 'ETC-Tolling', 'Tachograph-Regulation-EC-561', 'WCO-Safe'],
    dataClassifications: ['cmr-number', 'vehicle-plate', 'driver-license', 'tachograph-data', 'toll-record', 'driver-pii'],
    redactionPreset: 'transport-road',
    accessTemplate: 'road-rbac',
    stampTemplate: 'road-audit',
    signalTypes: ['vehicle-departure', 'vehicle-arrival', 'cmr-issued', 'toll-event', 'tacho-event', 'border-crossing'],
    vaultNamespace: 'transport-road',
    identifierFormats: ['cmr-9-digit', 'iso-6346-container', 'license-plate', 'tachograph-card', 'adr-un-number'],
    containerTypes: ['trailer-curtain', 'trailer-box', 'trailer-flatbed', 'trailer-tank', 'trailer-refrigerated'],
    complianceNotes: [
      'CMR consignment notes must be uniquely numbered and signed by sender, carrier, and consignee',
      'Driver hours must comply with EC 561/2006 — daily driving time ≤ 9 hours, weekly ≤ 56 hours',
      'ADR dangerous goods shipments require UN number, hazard class, packing group, and tunnel restriction code',
      'Tachograph data is legally binding and must be integrity-protected from driver to fleet operator',
      'Cross-border road transport requires customs transit document (T1/T2) with timestamped acceptance',
      'Toll transactions must include vehicle plate, timestamp, and route segment for audit and dispute resolution',
    ],
  },
  rail: {
    id: 'rail',
    name: 'Rail Freight',
    description: 'Rail freight operations, wagon tracking, CIM consignment notes, rail dangerous goods (RID), and cross-border rail corridor management.',
    frameworks: ['COTIF-CIM', 'RID-2023', 'ERA-Telemetry', 'OSJD-SMGS', 'TEN-T-Corridors'],
    dataClassifications: ['cim-number', 'wagon-number', 'train-id', 'rail-corridor', 'rail-consignment', 'rail-pii'],
    redactionPreset: 'transport-rail',
    accessTemplate: 'rail-rbac',
    stampTemplate: 'rail-audit',
    signalTypes: ['train-departure', 'train-arrival', 'wagon-coupled', 'wagon-decoupled', 'cim-issued', 'border-handover'],
    vaultNamespace: 'transport-rail',
    identifierFormats: ['cim-12-digit', 'wagon-12-digit-uic', 'smgs-consignment', 'train-path-id'],
    containerTypes: ['wagon-box', 'wagon-flat', 'wagon-hopper', 'wagon-tank', 'wagon-intermodal'],
    complianceNotes: [
      'CIM consignment notes must follow COTIF Appendix B format with carrier liability declaration',
      'Wagon numbers must follow UIC 12-digit format with check digit (modulo 11)',
      'RID dangerous goods shipments requireRID-consignment document with UN number and class',
      'Cross-border rail handovers require SMGS or CIM consignment with timestamped acceptance',
      'Train path allocations must be reserved with infrastructure manager and logged for audit',
    ],
  },
  multimodal: {
    id: 'multimodal',
    name: 'Multimodal & Combined Transport',
    description: 'Combined sea-air-rail-road freight with FBL multimodal Bill of Lading, intermodal container tracking, and end-to-end chain of custody.',
    frameworks: ['UNCTAD-MTO', 'FIATA-FBL', 'Rotterdam-Rules', 'UNECE-Convention-1980', 'WCO-TIR'],
    dataClassifications: ['fbl-number', 'intermodal-consignment', 'tir-carnet', 'transit-document', 'handover-record', 'forwarder-pii'],
    redactionPreset: 'transport-multimodal',
    accessTemplate: 'multimodal-rbac',
    stampTemplate: 'multimodal-audit',
    signalTypes: ['mode-handover', 'fbl-issued', 'tir-validated', 'transit-cleared', 'chain-of-custody', 'delivery-confirmation'],
    vaultNamespace: 'transport-multimodal',
    identifierFormats: ['fbl-9-digit', 'tir-carnet-11-digit', 'iso-6346-container', 'unlocode'],
    containerTypes: ['iso-container-20ft', 'iso-container-40ft', 'swap-body', 'semi-trailer', 'pallet'],
    complianceNotes: [
      'FBL multimodal Bill of Lading must declare liability regime per leg (sea/air/rail/road)',
      'TIR carnets must be validated at each customs office with timestamped acceptance',
      'Chain of custody records must capture every mode handover with carrier identity and seal verification',
      'Intermodal containers must track ISO 6346 number across all mode transitions',
      'End-to-end delivery confirmation requires consignee signature and timestamp proof',
    ],
  },
};

export const MODE_IDS = Object.keys(MODES);
